.TH CVSSUCK 1 "25 September 2000"

.SH NAME
cvssuck \- inefficient cvs repository grabber using cvs command

.SH SYNOPSIS
.B cvssuck
.RB [ -h ]
.RB [ -b ]
.RB [ -s ]
.RB [ -o 
.IR output-directory ]
.RB [ -l 
.IR lock-directory ]
.I cvsroot module

.SH DESCRIPTION
  CVSsuck grabs
.I module
in 
.IR cvsroot .

  CVSsuck is a mirroring tool for cvs repositories.
Unlike other tools such as CVSup or rsync,
it uses cvs command to access the repository.
So, it works well with remote repositories without
a special server or shell account.
However it is inefficient because
cvs client/server protocol is not designed for mirroring.
If a server provides special way to grab a repository,
you shouldn't use CVSsuck.

.SH OPTIONS
.TP
.B \-h
prints help message.

.TP
.B \-b
makes CVSsuck to traverse directories breadth first.
The default is depth first traverse.

.TP
.B \-s
specifies skeleton mode.
In this mode, CVSsuck grabs only 
first revision of the trunk, 1.1, branchpoints, head of branches and tagged revisions.
Note that first two (first revision of the trunk and 1.1) is identical in usual case.

.TP
.BI \-o " output-directory"
specifies output directory.
The default is 
.IR module .

.TP
.BI \-l " lock-directory"
specifies CVS style lock directory corresponding to
.IR output-directory .
The default is same as
.I output-directory 
(or
.I moudle
if the option
.B \-o
is not specified).


.SH EXAMPLES
.B "% cvssuck :pserver:anonymous@cvs.m17n.org:/cvs/cvs cvssuck"

  This grabs the module
.B cvssuck
in the repository
.B :pserver:anonymous@cvs.m17n.org:/cvs/cvs
into the directory
.B cvssuck.

.SH SEE ALSO
.BR cvs ( 1 ),
.BR rcs ( 1 ),
.BR cvsup ( 1 ),
.BR rsync ( 1 )

.SH AUTHORS
Tanaka Akira <akr@m17n.org>.

.SH BUGS
It's inefficient.

