.TH CVSSUCK 1 "25 September 2000"

.SH NAME
cvssuck \- inefficient cvs repository grabber using cvs command

.SH SYNOPSIS
.B cvssuck
.RB [ -h ]
.RB [ -b ]
.RB [ -s ]
.RB [ -v ]
.RB [ -D
.IR debug-option ",...]"
.I cvsroot
.RB [ -o
.I output-directory\f1|\f3\-O
.IR output-base ]
.RB [ -l 
.I lock-directory\f1|\f3\-L
.IR lock-base ]
.I module \f1...

.SH DESCRIPTION
.B CVSsuck
is a mirroring tool for cvs repositories.
Unlike other tools such as CVSup or rsync,
it uses cvs command to access the repository.
So, it works well with remote repositories without
a special server or shell account.
However it is inefficient because
cvs client/server protocol is not designed for mirroring.
If a server provides special way to grab a repository,
you shouldn't use
.BR CVSsuck .

.SH OPTIONS
.TP
.B \-h
prints help message.

.TP
.B \-b
makes
.B CVSsuck
to traverse directories in breadth first.
.B CVSsuck
traverses directory in depth first by default.

.TP
.B \-s
specifies skeleton mode.
In this mode,
.B CVSsuck
grabs only 
first revision of the trunk, 1.1, branchpoints, head of branches and tagged revisions.
Note that first two (first revision of the trunk and 1.1) is identical in usual case.

.TP
.B \-v
makes CVSsuck verbosely.
This is same as 
.RB ` "-D command,attic,cvsout,leavetmp" '.

.TP
.BI \-D " debug-option"\\f1,...
specifies debug options.
Available debug options are 
.RB ` command "', `" attic "', `" protocollog "', `" cvsout "', `" verbose "' and `" leavetmp "'."

.TP
.BI \-o " output-directory"
specifies the directory to store grabbed repository.
A remote RCS file 
.IR module / dir / file ,v
in
.I cvsroot
will be stored in
.IR output-directory / dir / file ,v.

.TP
.BI \-O " output-base"
specifies the base directory to store grabbed repository.
A remote RCS file 
.IR module / dir / file ,v
in
.I cvsroot
will be stored in
.IR output-base / module / dir / file ,v.
.B \-o
and
.B \-O
is exclusive.
The last specified before
.I module
is effective.
By default,
.B CVSsuck
behaves as that current directory is specified with
.BR \-O .

.TP
.BI \-l " lock-directory"
specifies the directory of CVS style lock.

.TP
.BI \-L " lock-base"
specifies the base directory of CVS style lock.
.B \-l
and
.B \-L
is exclusive.
A lock directory should be specified after an output directory.
The last specified before
.I module
after an output directory
is effective.
By default,
.B CVSsuck
assumes a lock directory is same as output directory.

.SH EXAMPLES
.B "% cvssuck :pserver:anonymous@cvs.m17n.org:/cvs/cvs cvssuck"

  This grabs the module
.B cvssuck
in the repository
.B :pserver:anonymous@cvs.m17n.org:/cvs/cvs
into the directory
.B cvssuck.

.SH SEE ALSO
.BR cvs ( 1 ),
.BR rcs ( 1 ),
.BR cvsup ( 1 ),
.BR rsync ( 1 )

.SH AUTHORS
Tanaka Akira <akr@m17n.org>.

.SH BUGS
It's inefficient.

